language: rust
cache: cargo
sudo: false

rust:
  - nightly
  - beta
  - stable
  - 1.40.0

jobs:
  allow_failures:
    - rust: nightly

script:
  - rustup component add rustfmt clippy
  - cargo build --all-targets --no-default-features --verbose
  - cargo build --all-targets --verbose
  - cargo test --all-targets --verbose
  - cargo clippy --all-targets --all-features -- -D warnings
  - cargo fmt --all -- --check