language: rust
cache: cargo
sudo: false

rust:
  - nightly
  - beta
  - stable

script:
  - cargo build --verbose
  - cargo build --features=with-serde --verbose
  - cargo test --verbose
  - cargo test --features=with-serde --verbose
