[package]
name = "atom_syndication"
version = "0.5.7"
authors = ["James Hurst <jh.jameshurst@gmail.com>"]
description = "Library for serializing the Atom web content syndication format"
repository = "https://github.com/rust-syndication/atom"
documentation = "https://docs.rs/atom_syndication/"
license = "MIT/Apache-2.0"
readme = "README.md"
keywords = ["atom", "feed", "parser", "parsing"]
categories = ["parser-implementations"]
include = ["src/*", "Cargo.toml", "LICENSE-MIT", "LICENSE-APACHE", "README.md"]

[dependencies]
quick-xml = "0.10"
derive_builder = "0.5"
